# Generated by Django 5.2.7 on 2025-12-08 17:12

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem_capa', stdimage.models.StdImageField(force_min_size=False, upload_to='blog', variations={'thumb': (600, 400)}, verbose_name='Imagem de Capa')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao_curta', models.TextField(max_length=200, verbose_name='Descrição Curta')),
                ('descricao_longa', models.TextField(verbose_name='Descrição Longa')),
                ('icone', models.CharField(choices=[('icon-autorenew', 'Auto Renew'), ('icon-backspace', 'Backspace'), ('icon-av_timer', 'Timer'), ('icon-beenhere', 'Been Here'), ('icon-business_center', 'Business Center'), ('icon-cloud_done', 'Cloud Done'), ('icon-trending_up', 'Trending Up'), ('icon-people', 'People'), ('icon-security', 'Security'), ('icon-account_balance', 'Account Balance'), ('icon-pie_chart', 'Pie Chart'), ('icon-assessment', 'Assessment'), ('icon-shield', 'Shield')], default='icon-business', help_text='Escolha o ícone que aparece no site. Veja todos em: <a href="https://fonts.google.com/icons" target="_blank">fonts.google.com/icons</a>', max_length=50, verbose_name='Ícone (Material Icons)')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='testemunhos', variations={'thumb': (100, 100)}, verbose_name='Foto')),
                ('depoimento', models.TextField(verbose_name='Depoimento')),
            ],
            options={
                'verbose_name': 'Testemunho',
                'verbose_name_plural': 'Testemunhos',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': (300, 300)}, verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
